config/routes.rb
Rails.application.routes.draw do
  get "about/index"
  get "category/index"
  get "category/show"
  get "brand/index"
  get "brand/show"
  get "product/index"
  get "product/show"
  get "home/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  root "home#index"
  get "products", to: "product#index"
  get "product/:id", to: "product#show", as: "product"
  get "search", to: "product#search"
  get "brands", to: "brand#index"
  get "brand/:id", to: "brand#show", as: "brand"
  get "categories", to: "category#index"
  get "category/:id", to: "category#show", as: "category"
  get "about", to: "about#index"

  resources :product_type, only: [ :index ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/color.rb
class Color < ApplicationRecord
  has_many :product_color
  has_many :product, through: :product_color
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand
  belongs_to :product_type
  belongs_to :category
  has_many :product_tags
  has_many :tags, through: :product_tags
  has_many :product_color
  has_many :color, through: :product_colors
end

app/models/product_color.rb
class ProductColor < ApplicationRecord
  belongs_to :product
  belongs_to :color
end

app/models/product_tag.rb
class ProductTag < ApplicationRecord
  belongs_to :product
  belongs_to :tag
end

app/models/product_type.rb
class ProductType < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/brand_controller.rb
class BrandController < ApplicationController
  def index
    @brands = Brand.left_joins(:products)
                 .select("brands.*, COUNT(products.id) AS products_count")
                 .group("brands.id")
                 .page(params[:page]).per(15)
  end
  def show
    @brand = Brand.find(params[:id])
    @products = @brand.products
    @products = @products.page(params[:page]).per(15)
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  def index
    @categories = Category.left_joins(:products)
                 .select("categories.*, COUNT(products.id) AS products_count")
                 .group("categories.id")
                 .page(params[:page]).per(15)
  end
  def show
    @category = Category.find(params[:id])
    @products = @category.products
    @products = @products.page(params[:page]).per(15)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  def index
    @products = Product.page(params[:page]).per(15)
  end

  def show
    @product = Product.find(params[:id])
    color_ids = @product.product_color.pluck(:color_id)
    @colors = Color.where(id: color_ids)
  end

  def search
    @query = params[:query]
    @type = params[:type]

    @products = Product.where("name LIKE ?", "%#{@query}%")
    @products = @products.where(product_type: @type) unless @type == "all"
    @products = @products.page(params[:page]).per(15)

    render :index
  end
end

app/controllers/product_type_controller.rb
class ProductTypeController < ApplicationController
  def index
    @product_types = ProductType.all
    render json: @product_types
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brand_helper.rb
module BrandHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/product_type_helper.rb
module ProductTypeHelper
end

app/views/brand/index.html.erb
<div class="container">
  <h1 class="mt-5">Brands</h1>
  <table class="table table-striped table-hover mt-3">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col">Name</th>
        <th scope="col">Associated makeups</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @brands.each_with_index do |brand, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= brand.description %></td>
          <td><%= brand.products_count %></td>
          <td><%= link_to "View Products", brand_path(brand), class: "btn btn-primary" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="d-flex align-items-center justify-content-center">
    <%= paginate @brands %>
  </div>
</div>

app/views/brand/show.html.erb
<div class="container">
  <h1 class="mt-5">Products for <%= @brand.description %> brand</h1>
  <table class="table table-striped table-hover mt-3">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col">Image</th>
        <th scope="col">Name</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @products.each_with_index do |product, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><img src="<%= product.image %>" alt="<%= product.name %>" class="img-thumbnail" style="width: 100px;"></td>
          <td><%= product.name %></td>
          <td><%= link_to "Details", product_path(product), class: "btn btn-primary" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="d-flex align-items-center justify-content-center">
    <%= paginate @products %>
  </div>
</div>

app/views/category/index.html.erb
<div class="container">
  <h1 class="mt-5">Categories</h1>
  <table class="table table-striped table-hover mt-3">
    <thead>
      <tr>
        <th scope="col"></th>
        <th scope="col">Name</th>
        <th scope="col">Associated makeups</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each_with_index do |category, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= category.description %></td>
          <td><%= category.products_count %></td>
          <td><%= link_to "View Products", category_path(category), class: "btn btn-primary" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="d-flex align-items-center justify-content-center">
    <%= paginate @categories %>
  </div>
</div>

app/views/category/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= @category.description %> makeups</title>
  </head>
  <body>
    <div class="container">
      <h1 class="mt-5">Products for <%= @category.description %> </h1>
      <table class="table table-striped table-hover mt-3">
        <thead>
          <tr>
            <th scope="col"></th>
            <th scope="col">Image</th>
            <th scope="col">Name</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% @products.each_with_index do |product, index| %>
            <tr>
              <td><%= index + 1 %></td>
              <td><img src="<%= product.image %>" alt="<%= product.name %>" class="img-thumbnail" style="width: 100px;"></td>
              <td><%= product.name %></td>
              <td><%= link_to "Details", product_path(product), class: "btn btn-primary" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="d-flex align-items-center justify-content-center">
        <%= paginate @products %>
      </div>
    </div>
  </body>
</html>

app/views/product/index.html.erb
<div class="container">
  <h1 class="mt-5">Makeups</h1>
  <% if @products.any? %>
    <table class="table table-striped table-hover mt-3">
      <thead>
        <tr>
          <th scope="col"></th>
          <th scope="col">Image</th>
          <th scope="col">Name</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <% @products.each_with_index do |product, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><img src="<%= product.image %>" alt="<%= product.name %>" class="img-thumbnail" style="width: 100px;"></td>
            <td><%= product.name %></td>
            <td><%= link_to "Details", product_path(product), class: "btn btn-primary" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="d-flex align-items-center justify-content-center">
      <%= paginate @products %>
    </div>
  <% else %>
    <p>No records were found for your search.</p>
  <% end %>
</div>

app/views/product/show.html.erb
<div class="container mt-5">
  <h1><%= @product.name %></h1>
  <div class="row mt-4">
    <div class="col-md-4">
      <img src="<%= @product.image %>" alt="<%= @product.name %>" class="img-fluid">
    </div>
    <div class="col-md-8">
      <h3>Details</h3>
      <ul class="list-group">
        <li class="list-group-item"><strong>Price:</strong> <%= number_to_currency(@product.price) %>  <%= @product.currency %></li>
        <li class="list-group-item"><strong>Type:</strong> <%= @product.product_type.description %></li>
        <li class="list-group-item"><strong>Brand:</strong> <%= @product.brand.description %></li>
        <li class="list-group-item"><strong>Category:</strong> <%= @product.category.description %></li>
        <li class="list-group-item"><strong>Colors availables:</strong>
          <div style="display: inline-flex; gap: 10px;">
            <% @colors.each do |color| %>
              <div style="width: 30px; height: 30px; border-radius: 50%; background-color: <%= color.hex_value %>; border: 1px solid #ccc;"></div>
            <% end %>
          </div>
        </li>
        <li class="list-group-item"><strong>Description:</strong> <%= @product.description %></li>
        <li class="list-group-item"><%= link_to "Check the website", @product.link, class: "btn btn-primary" %></li>
      </ul>
    </div>
  </div>
</div>